name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest 
    steps:
   
      - name: Test variable
        run: echo ${{ vars.IMAGE_NAME }}

      - name: checkout code
        uses: actions/checkout@v3

      - name: Build image 
        run: docker build -t  ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }} .
      

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push to docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}

  deploy-to-ec2:
      runs-on: ubuntu-latest

      needs: build-and-push

      steps: 

        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_PRIVATE_KEY }}
            script: |
              sudo docker ps
              sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}
              sudo docker stop nodejs-containers
              sudo docker rm -f nodejs-containers
              sudo docker run -d --name nodejs-containers -p 3001:3000 ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}
#26b27c53911219825e0fefe739ea4eb072ebaed044521ab3bd7f1541776fb601
#26b27c539112
