name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
   
      - name: Clone project into this runner
        uses: actions/checkout@v3

      - name: Build image from dockerfile
        run: docker build -t  my-image .
      
      - name: Tag image
        run: docker tag my-image wesines/my-image

      - name: Verify build image
        run : docker images

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}