name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  job-0:
    runs-on: ubuntu-latest
    steps:
   
      - name: Clone project 
        uses: actions/checkout@v3

      - name: Run script 
        run: echo hello

  job-1:

    runs-on: ubuntu-latest

    needs: [job-0]

    steps:
      
      - name: Clone project 
        uses: actions/checkout@v3

      - name: Run script 
        run: echo hello


  job-2:

    runs-on: ubuntu-latest

    needs: [job-0]

    steps:

      - name: Run script 
        run: echo hello


  job-3:

    runs-on: ubuntu-latest

    needs: [job-1,job-2]

    steps:

      - name: Run script 
        run: echo hello


  job-4:

    runs-on: ubuntu-latest

    needs: [job-3]

    steps:
     
      - name: Clone project 
        uses: actions/checkout@v3

  
      - name: Run script 1 of job 2
        run: echo script-1-message of job 2