name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
   
      - name: Clone project into this runner
        uses: actions/checkout@v3

      - name: Build image from dockerfile
        run: docker build -t my-image .